// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuizAPI.Data;

namespace QuizAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200421114156_Tutorials update 2020.3")]
    partial class Tutorialsupdate20203
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("QuizAPI.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("NickName");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("QuizAPI.Models.BaseUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<DateTime>("RegisteredOn");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("User");
                });

            modelBuilder.Entity("QuizAPI.Models.Course.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddedById");

                    b.Property<string>("Code");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("Name");

                    b.Property<long>("Size");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.ImageAnswers.ImageAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Choosable");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<int>("GroupId");

                    b.Property<string>("Name");

                    b.Property<int?>("RootId");

                    b.Property<long>("Size");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("RootId");

                    b.ToTable("ImageAnswers");
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.ImageAnswers.ImageAnswerGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ImageAnswerGroups");
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.InterpretedImages.InterpretedImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<int>("GroupId");

                    b.Property<int>("JumpId");

                    b.Property<int>("LeftId");

                    b.Property<int>("RationOfGradientsId");

                    b.Property<int>("RightId");

                    b.Property<long>("Size");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("JumpId");

                    b.HasIndex("LeftId");

                    b.HasIndex("RationOfGradientsId");

                    b.HasIndex("RightId");

                    b.ToTable("InterpretedImages");
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.InterpretedImages.InterpretedImageGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("InterpretedImageGroups");
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.InterpretedImages.JumpValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("JumpValues");
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.InterpretedImages.LeftGradientValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("LeftGradientValues");
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.InterpretedImages.RationOfGradientsValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("RationOfGradientsValues");
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.InterpretedImages.RightGradientValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("RightGradientValues");
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.Keyboard.Keyboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Keyboards");
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.Keyboard.KeyboardNumericKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("TextPresentation");

                    b.HasKey("Id");

                    b.ToTable("NumericKeys");
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.Keyboard.KeyboardNumericKeyRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("KeySimpleForm");

                    b.Property<int>("KeyboardId");

                    b.Property<int>("NumericKeyId");

                    b.HasKey("Id");

                    b.HasIndex("KeyboardId");

                    b.HasIndex("NumericKeyId");

                    b.ToTable("KeyboardNumericKeyRelation");
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.Keyboard.KeyboardVariableKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("TextPresentation");

                    b.HasKey("Id");

                    b.ToTable("VariableKeys");
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.Keyboard.KeyboardVariableKeyRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<int>("KeyboardId");

                    b.Property<int>("VariableKeyId");

                    b.HasKey("Id");

                    b.HasIndex("KeyboardId");

                    b.HasIndex("VariableKeyId");

                    b.ToTable("KeyboardVariableKeyRelation");
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.Keyboard.VariableKeyVariableChar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<int>("KeyId");

                    b.Property<string>("VariableChar");

                    b.HasKey("Id");

                    b.HasIndex("KeyId");

                    b.ToTable("VariableKeyVariableChar");
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.Keyboard.VariableKeyVariableCharValidValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CharId");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<bool>("IsLatex");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CharId");

                    b.ToTable("VariableKeyVariableCharValidValues");
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.LevelsOfDifficulty.LevelOfDifficulty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("HexColor");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("LevelsOfDifficulty");
                });

            modelBuilder.Entity("QuizAPI.Models.QuestionChallenges.ChallengePlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("Name");

                    b.Property<string>("Score");

                    b.Property<int>("SessionId");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ChallengePlayer");
                });

            modelBuilder.Entity("QuizAPI.Models.QuestionChallenges.ChallengeSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<int>("TemplateId");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("ChallengeSessions");
                });

            modelBuilder.Entity("QuizAPI.Models.QuestionChallenges.QuestionChallengeQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ChallengeTemplateId");

                    b.Property<int?>("ClickableQuestionId");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<int?>("KeyboardQuestionId");

                    b.Property<int>("Order");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeTemplateId");

                    b.HasIndex("ClickableQuestionId");

                    b.HasIndex("KeyboardQuestionId");

                    b.ToTable("QuestionChallengeQuestion");
                });

            modelBuilder.Entity("QuizAPI.Models.QuestionChallenges.QuestionChallengeSingleResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<int>("PlayerId");

                    b.Property<string>("Result");

                    b.Property<int>("SessionId");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SessionId");

                    b.ToTable("QuestionChallengeSingleResult");
                });

            modelBuilder.Entity("QuizAPI.Models.QuestionChallenges.QuestionChallengeTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<int>("TimeInMinutes");

                    b.HasKey("Id");

                    b.ToTable("QuestionChallengeTemplates");
                });

            modelBuilder.Entity("QuizAPI.Models.QuestionGroupsSubgroup.ClickableQuestionSubgroupRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<int>("QuestionId");

                    b.Property<int>("SubgroupId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SubgroupId");

                    b.ToTable("ClickableQuestionSubgroupRelation");
                });

            modelBuilder.Entity("QuizAPI.Models.QuestionGroupsSubgroup.QuestionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CourseId");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("Name");

                    b.Property<long>("Size");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("QuestionGroups");
                });

            modelBuilder.Entity("QuizAPI.Models.QuestionGroupsSubgroup.QuestionSubgroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<int>("GroupId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("QuestionSubgroups");
                });

            modelBuilder.Entity("QuizAPI.Models.Questions.KeyboardQuestion.KeyboardQuestionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<int>("QuestionId");

                    b.Property<string>("TextAnswer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("KeyboardQuestionAnswer");
                });

            modelBuilder.Entity("QuizAPI.Models.Questions.QuestionAttribure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("Name");

                    b.Property<int>("QuestionBaseId");

                    b.Property<int?>("QuestionTemplateBaseId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionBaseId");

                    b.HasIndex("QuestionTemplateBaseId");

                    b.ToTable("QuestionAttribure");
                });

            modelBuilder.Entity("QuizAPI.Models.Questions.QuestionBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddedById");

                    b.Property<bool>("Approved");

                    b.Property<string>("Code");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("LevelOfDifficultyId");

                    b.Property<long>("PDFSize");

                    b.Property<string>("PDFURL");

                    b.Property<bool>("Public");

                    b.Property<int>("SubtopicId");

                    b.Property<long>("ThumbnailSize");

                    b.Property<string>("ThumbnailURL");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("LevelOfDifficultyId");

                    b.HasIndex("SubtopicId");

                    b.ToTable("QuestionBase");

                    b.HasDiscriminator<string>("Discriminator").HasValue("QuestionBase");
                });

            modelBuilder.Entity("QuizAPI.Models.Questions.SimpleClickableQuestion.ClickChart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnswerGroupId");

                    b.Property<int>("AnswerId");

                    b.Property<int>("AnswerWeight");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<int>("Height");

                    b.Property<int?>("SimpleClickableQuestionId");

                    b.Property<int>("Width");

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.HasKey("Id");

                    b.HasIndex("AnswerGroupId");

                    b.HasIndex("AnswerId");

                    b.HasIndex("SimpleClickableQuestionId");

                    b.ToTable("ClickChart");
                });

            modelBuilder.Entity("QuizAPI.Models.Questions.SimpleClickableQuestion.ClickEquation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnswerWeight");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<int>("Height");

                    b.Property<int?>("SimpleClickableQuestionId");

                    b.Property<int>("Width");

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.HasKey("Id");

                    b.HasIndex("SimpleClickableQuestionId");

                    b.ToTable("ClickEquation");
                });

            modelBuilder.Entity("QuizAPI.Models.Questions.SimpleClickableQuestion.ClickImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnswerGroupId");

                    b.Property<int>("AnswerId");

                    b.Property<int>("AnswerWeight");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<int>("Height");

                    b.Property<int>("QuestionId");

                    b.Property<int>("Width");

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.HasKey("Id");

                    b.HasIndex("AnswerGroupId");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("ClickImage");
                });

            modelBuilder.Entity("QuizAPI.Models.QuestionTemplates.QuestionTemplateBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<int>("LevelOfDifficultyId");

                    b.Property<int>("SubtopicId");

                    b.HasKey("Id");

                    b.HasIndex("LevelOfDifficultyId");

                    b.HasIndex("SubtopicId");

                    b.ToTable("QuestionTemplateBases");
                });

            modelBuilder.Entity("QuizAPI.Models.Topic.Subtopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("Name");

                    b.Property<int>("TopicId");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Subtopics");
                });

            modelBuilder.Entity("QuizAPI.Models.Topic.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("QuizAPI.Models.Tutorials.Tutorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddedById");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<int>("GroupId");

                    b.Property<string>("Name");

                    b.Property<int>("Reviews");

                    b.Property<long>("Size");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("GroupId");

                    b.ToTable("Tutorial");
                });

            modelBuilder.Entity("QuizAPI.Models.Tutorials.TutorialPDF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<long>("PDFSize");

                    b.Property<string>("PDFURL");

                    b.Property<string>("Title");

                    b.Property<int>("TutorialId");

                    b.HasKey("Id");

                    b.HasIndex("TutorialId");

                    b.ToTable("TutorialPDF");
                });

            modelBuilder.Entity("QuizAPI.Models.Tutorials.TutorialsGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CourseId");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("TutorialsGroup");
                });

            modelBuilder.Entity("QuizAPI.Models.Tutorials.TutorialStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("Info");

                    b.Property<int>("Order");

                    b.Property<long>("Size");

                    b.Property<int>("TutorialId");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.HasIndex("TutorialId");

                    b.ToTable("TutorialStep");
                });

            modelBuilder.Entity("QuizAPI.Models.Tutorials.TutorialTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("Tag");

                    b.Property<int>("TutorialId");

                    b.HasKey("Id");

                    b.HasIndex("TutorialId");

                    b.ToTable("TutorialTag");
                });

            modelBuilder.Entity("QuizAPI.Models.Tutorials.TutorialVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<string>("Discription");

                    b.Property<string>("Title");

                    b.Property<int>("TutorialId");

                    b.Property<long>("VideoSize");

                    b.Property<string>("VideoURL");

                    b.HasKey("Id");

                    b.HasIndex("TutorialId");

                    b.ToTable("TutorialVideo");
                });

            modelBuilder.Entity("QuizAPI.Models.Questions.KeyboardQuestion.KeyboardQuestion", b =>
                {
                    b.HasBaseType("QuizAPI.Models.Questions.QuestionBase");

                    b.Property<string>("AnswerForLatex");

                    b.Property<long>("ImageSize");

                    b.Property<string>("ImageURL");

                    b.Property<int>("KeyboardId");

                    b.HasIndex("KeyboardId");

                    b.ToTable("KeyboardQuestion");

                    b.HasDiscriminator().HasValue("KeyboardQuestion");
                });

            modelBuilder.Entity("QuizAPI.Models.Questions.SimpleClickableQuestion.SimpleClickableQuestion", b =>
                {
                    b.HasBaseType("QuizAPI.Models.Questions.QuestionBase");

                    b.Property<int>("BackgroundImageHeight");

                    b.Property<int>("BackgroundImageSize");

                    b.Property<string>("BackgroundImageURL");

                    b.Property<int>("BackgroundImageWidth");

                    b.ToTable("SimpleClickableQuestion");

                    b.HasDiscriminator().HasValue("SimpleClickableQuestion");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QuizAPI.Models.BaseUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QuizAPI.Models.BaseUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuizAPI.Models.BaseUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QuizAPI.Models.BaseUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.Course.Course", b =>
                {
                    b.HasOne("QuizAPI.Models.BaseUser", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.ImageAnswers.ImageAnswer", b =>
                {
                    b.HasOne("QuizAPI.Models.DefaultValues.ImageAnswers.ImageAnswerGroup", "Group")
                        .WithMany("Images")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuizAPI.Models.DefaultValues.ImageAnswers.ImageAnswer", "Root")
                        .WithMany("Leafs")
                        .HasForeignKey("RootId");
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.InterpretedImages.InterpretedImage", b =>
                {
                    b.HasOne("QuizAPI.Models.DefaultValues.InterpretedImages.InterpretedImageGroup", "Group")
                        .WithMany("Images")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuizAPI.Models.DefaultValues.InterpretedImages.JumpValue", "Jump")
                        .WithMany()
                        .HasForeignKey("JumpId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuizAPI.Models.DefaultValues.InterpretedImages.LeftGradientValue", "Left")
                        .WithMany()
                        .HasForeignKey("LeftId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuizAPI.Models.DefaultValues.InterpretedImages.RationOfGradientsValue", "RationOfGradients")
                        .WithMany()
                        .HasForeignKey("RationOfGradientsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuizAPI.Models.DefaultValues.InterpretedImages.RightGradientValue", "Right")
                        .WithMany()
                        .HasForeignKey("RightId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.Keyboard.KeyboardNumericKeyRelation", b =>
                {
                    b.HasOne("QuizAPI.Models.DefaultValues.Keyboard.Keyboard", "Keyboard")
                        .WithMany("NumericKeys")
                        .HasForeignKey("KeyboardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuizAPI.Models.DefaultValues.Keyboard.KeyboardNumericKey", "NumericKey")
                        .WithMany("Relations")
                        .HasForeignKey("NumericKeyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.Keyboard.KeyboardVariableKeyRelation", b =>
                {
                    b.HasOne("QuizAPI.Models.DefaultValues.Keyboard.Keyboard", "Keyboard")
                        .WithMany("VariableKeys")
                        .HasForeignKey("KeyboardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuizAPI.Models.DefaultValues.Keyboard.KeyboardVariableKey", "VariableKey")
                        .WithMany("Relations")
                        .HasForeignKey("VariableKeyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.Keyboard.VariableKeyVariableChar", b =>
                {
                    b.HasOne("QuizAPI.Models.DefaultValues.Keyboard.KeyboardVariableKey", "Key")
                        .WithMany("VariablesChars")
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.DefaultValues.Keyboard.VariableKeyVariableCharValidValues", b =>
                {
                    b.HasOne("QuizAPI.Models.DefaultValues.Keyboard.VariableKeyVariableChar", "Char")
                        .WithMany("ValidValues")
                        .HasForeignKey("CharId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.QuestionChallenges.ChallengePlayer", b =>
                {
                    b.HasOne("QuizAPI.Models.QuestionChallenges.ChallengeSession", "Session")
                        .WithMany("Players")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.QuestionChallenges.ChallengeSession", b =>
                {
                    b.HasOne("QuizAPI.Models.QuestionChallenges.QuestionChallengeTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.QuestionChallenges.QuestionChallengeQuestion", b =>
                {
                    b.HasOne("QuizAPI.Models.QuestionChallenges.QuestionChallengeTemplate", "ChallengeTemplate")
                        .WithMany("Questions")
                        .HasForeignKey("ChallengeTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuizAPI.Models.Questions.SimpleClickableQuestion.SimpleClickableQuestion", "ClickableQuestion")
                        .WithMany()
                        .HasForeignKey("ClickableQuestionId");

                    b.HasOne("QuizAPI.Models.Questions.KeyboardQuestion.KeyboardQuestion", "KeyboardQuestion")
                        .WithMany()
                        .HasForeignKey("KeyboardQuestionId");
                });

            modelBuilder.Entity("QuizAPI.Models.QuestionChallenges.QuestionChallengeSingleResult", b =>
                {
                    b.HasOne("QuizAPI.Models.QuestionChallenges.ChallengePlayer", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuizAPI.Models.QuestionChallenges.ChallengeSession", "Session")
                        .WithMany("Results")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.QuestionGroupsSubgroup.ClickableQuestionSubgroupRelation", b =>
                {
                    b.HasOne("QuizAPI.Models.Questions.SimpleClickableQuestion.SimpleClickableQuestion", "Question")
                        .WithMany("ClickableSubgroupRelations")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuizAPI.Models.QuestionGroupsSubgroup.QuestionSubgroup", "Subgroup")
                        .WithMany("ClickableSubgroupRelations")
                        .HasForeignKey("SubgroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.QuestionGroupsSubgroup.QuestionGroup", b =>
                {
                    b.HasOne("QuizAPI.Models.Course.Course", "Course")
                        .WithMany("QuestionGroups")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.QuestionGroupsSubgroup.QuestionSubgroup", b =>
                {
                    b.HasOne("QuizAPI.Models.QuestionGroupsSubgroup.QuestionGroup", "Group")
                        .WithMany("Subgroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.Questions.KeyboardQuestion.KeyboardQuestionAnswer", b =>
                {
                    b.HasOne("QuizAPI.Models.Questions.KeyboardQuestion.KeyboardQuestion", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.Questions.QuestionAttribure", b =>
                {
                    b.HasOne("QuizAPI.Models.Questions.QuestionBase", "QuestionBase")
                        .WithMany("QuestionAttribures")
                        .HasForeignKey("QuestionBaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuizAPI.Models.QuestionTemplates.QuestionTemplateBase")
                        .WithMany("QuestionAttribures")
                        .HasForeignKey("QuestionTemplateBaseId");
                });

            modelBuilder.Entity("QuizAPI.Models.Questions.QuestionBase", b =>
                {
                    b.HasOne("QuizAPI.Models.BaseUser", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("QuizAPI.Models.DefaultValues.LevelsOfDifficulty.LevelOfDifficulty", "LevelOfDifficulty")
                        .WithMany()
                        .HasForeignKey("LevelOfDifficultyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuizAPI.Models.Topic.Subtopic", "Subtopic")
                        .WithMany()
                        .HasForeignKey("SubtopicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.Questions.SimpleClickableQuestion.ClickChart", b =>
                {
                    b.HasOne("QuizAPI.Models.DefaultValues.InterpretedImages.InterpretedImageGroup", "AnswerGroup")
                        .WithMany()
                        .HasForeignKey("AnswerGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuizAPI.Models.DefaultValues.InterpretedImages.InterpretedImage", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuizAPI.Models.Questions.SimpleClickableQuestion.SimpleClickableQuestion")
                        .WithMany("ClickCharts")
                        .HasForeignKey("SimpleClickableQuestionId");
                });

            modelBuilder.Entity("QuizAPI.Models.Questions.SimpleClickableQuestion.ClickEquation", b =>
                {
                    b.HasOne("QuizAPI.Models.Questions.SimpleClickableQuestion.SimpleClickableQuestion")
                        .WithMany("ClickEquations")
                        .HasForeignKey("SimpleClickableQuestionId");
                });

            modelBuilder.Entity("QuizAPI.Models.Questions.SimpleClickableQuestion.ClickImage", b =>
                {
                    b.HasOne("QuizAPI.Models.DefaultValues.ImageAnswers.ImageAnswerGroup", "AnswerGroup")
                        .WithMany()
                        .HasForeignKey("AnswerGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuizAPI.Models.DefaultValues.ImageAnswers.ImageAnswer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuizAPI.Models.Questions.SimpleClickableQuestion.SimpleClickableQuestion", "Question")
                        .WithMany("ClickImages")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.QuestionTemplates.QuestionTemplateBase", b =>
                {
                    b.HasOne("QuizAPI.Models.DefaultValues.LevelsOfDifficulty.LevelOfDifficulty", "LevelOfDifficulty")
                        .WithMany()
                        .HasForeignKey("LevelOfDifficultyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuizAPI.Models.Topic.Subtopic", "Subtopic")
                        .WithMany()
                        .HasForeignKey("SubtopicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.Topic.Subtopic", b =>
                {
                    b.HasOne("QuizAPI.Models.Topic.Topic", "Topic")
                        .WithMany("Subtopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.Tutorials.Tutorial", b =>
                {
                    b.HasOne("QuizAPI.Models.BaseUser", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("QuizAPI.Models.Tutorials.TutorialsGroup", "Group")
                        .WithMany("Tutorials")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.Tutorials.TutorialPDF", b =>
                {
                    b.HasOne("QuizAPI.Models.Tutorials.Tutorial", "Tutorial")
                        .WithMany("PDFs")
                        .HasForeignKey("TutorialId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.Tutorials.TutorialsGroup", b =>
                {
                    b.HasOne("QuizAPI.Models.Course.Course")
                        .WithMany("TutorialsGroups")
                        .HasForeignKey("CourseId");
                });

            modelBuilder.Entity("QuizAPI.Models.Tutorials.TutorialStep", b =>
                {
                    b.HasOne("QuizAPI.Models.Tutorials.Tutorial", "Tutorial")
                        .WithMany("TutorialSteps")
                        .HasForeignKey("TutorialId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.Tutorials.TutorialTag", b =>
                {
                    b.HasOne("QuizAPI.Models.Tutorials.Tutorial", "Tutorial")
                        .WithMany("Tags")
                        .HasForeignKey("TutorialId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.Tutorials.TutorialVideo", b =>
                {
                    b.HasOne("QuizAPI.Models.Tutorials.Tutorial", "Tutorial")
                        .WithMany("Videos")
                        .HasForeignKey("TutorialId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuizAPI.Models.Questions.KeyboardQuestion.KeyboardQuestion", b =>
                {
                    b.HasOne("QuizAPI.Models.DefaultValues.Keyboard.Keyboard", "Keyboard")
                        .WithMany()
                        .HasForeignKey("KeyboardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
