const QUESTIONNAIRE_QUESTION_MC_NORMAL_TYPE = 2
const QUESTIONNAIRE_QUESTION_MC_TEXT_TYPE = 4
const QUESTIONNAIRE_QUESTION_MC_RANGE_TYPE = 8

export const QUESTIONNAIRE_QUESTION_MC_TYPE = {
    NORMAL:QUESTIONNAIRE_QUESTION_MC_NORMAL_TYPE,
    TXT:QUESTIONNAIRE_QUESTION_MC_TEXT_TYPE,
    RANGE:QUESTIONNAIRE_QUESTION_MC_RANGE_TYPE,
}

